function(MAKE_VOICE_LIST VOX_LIST)
  set(voice_list_file ${CMAKE_CURRENT_SOURCE_DIR}/flite_voice_list.c)
  file(WRITE ${voice_list_file} "/* Generated automatically from make_voice_list */\n\n")
  file(APPEND ${voice_list_file} "#include \"flite.h\"\n\n")
  foreach(voice ${VOX_LIST})
     file(APPEND ${voice_list_file} "cst_voice *register_${voice}(const char *voxdir);\n")
  endforeach(voice)

  file(APPEND ${voice_list_file} "\n")
  file(APPEND ${voice_list_file} "cst_val *flite_set_voice_list(const char *voxdir)\n")
  file(APPEND ${voice_list_file} "{\n")
  foreach(voice ${VOX_LIST})
     file(APPEND ${voice_list_file} "   flite_voice_list = cons_val(voice_val(register_${voice}(voxdir)), flite_voice_list);\n")
  endforeach(voice)
  if(VOX_LIST)
     file(APPEND ${voice_list_file} "   flite_voice_list = val_reverse(flite_voice_list);\n")
     file(APPEND ${voice_list_file} "   return flite_voice_list;\n")
  endif(VOX_LIST)

  file(APPEND ${voice_list_file} "}\n\n")
endfunction(MAKE_VOICE_LIST)
